# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b6f2d1c993fed52766ad8137ed0fd3508963c4876e9374ca5b7eed130f15f9eac3244c2c610c0eca8801c004c0d20048eab1d1a55eb21aac6b1c5624dea03f0

test:
  secret_key_base: efd9ec600cbe4940ad0c3d0131a1ece3dadc5c908730b72f919738af93b7809af1ad1dd647e31509c4b34de37450e053731f16748537438b22ee777a789eb7e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: bendod600cbe4940ad0c3d0131a1ece3dadc5c908730b72f9bendodf93b7809af1ad1dd647e31509c4b34de37450e053731f16748537438b22ee777a78bendod
